debug tests
vstebletsov89/go-developer-course-diploma pull request #1
Opened 2022-04-18 15:50 UTC by vstebletsov89

2022-04-25 16:37 UTC, sergeysergeevru commented on internal/app/controller/handlers.go
> +	PROCESSED  = "PROCESSED"
В гошке принято использовать camelcase для констант. Не то чтобы это плохо, но так диктует комьюнити :)

2022-04-25 16:52 UTC, sergeysergeevru commented on internal/app/controller/handlers.go
> +func WriteJSON(w http.ResponseWriter, response interface{}, logger *logrus.Logger) {
можно сделать методом Controller, тогда можно из аргументов убрать logger

2022-04-25 16:57 UTC, sergeysergeevru commented on internal/app/controller/handlers.go
> +}
по сути это тоже самое, что хранить пароль в открытом виде. hex просто кодирует, это не криптографическое преобразование. https://go.dev/play/p/WbNkBGnQ9a5
Это довольно критичная проблема для реального приложения, поэтому давай сделаем безопасно.

2022-04-25 16:59 UTC, sergeysergeevru commented on internal/app/controller/handlers.go
> +		if err := json.NewDecoder(r.Body).Decode(&user); err != nil {
user у тебя и так указатель
```suggestion
		if err := json.NewDecoder(r.Body).Decode(user); err != nil {
```

2022-04-25 17:01 UTC, sergeysergeevru commented on internal/app/controller/handlers.go
> +		}
Можно переставить порядок, тогда кучу условий с errors.Is не надо `errors.Is(nil, repository.ErrorUserAlreadyExist)` всегда будет false :)
```suggestion
		if errors.Is(err, repository.ErrorUserAlreadyExist) {
			WriteError(w, http.StatusConflict, err)
			return
		}
		if err != nil  {
			c.Logger.Infof("RegisterUser error: %s", err)
			WriteError(w, http.StatusInternalServerError, err)
			return
		}
```

2022-04-25 17:04 UTC, sergeysergeevru commented on internal/app/service/auth/auth.go
> +		b[i] = letterRunes[rand.Intn(len(letterRunes))]
для сессии использовать math/random я бы не стал, он не достаточно надежен. Желательно перейти на crypto, либо можно посмотреть в сторону UUID v4 или GUID.

2022-04-25 17:07 UTC, sergeysergeevru commented on internal/app/service/auth/auth.go
> +		cookie, _ := r.Cookie(cookieName)
ошибку надо проверить обязательно

2022-04-25 17:07 UTC, sergeysergeevru commented on internal/app/service/auth/auth.go
> +var _ secure.UserAuthorization = (*UserAuthorizationStore)(nil)
эта тема классная, молодец!

2022-04-25 17:20 UTC, sergeysergeevru commented on internal/app/service/auth/auth.go
> +	sessions map[string]Session
хранилище сессий можно обернуть в абстракцию, чтобы наружу торчали методы положить и достать по ключу. Тогда можно будет разные хранилища подключать: inmemory, база, redis. В общем все что душе угодно

2022-04-25 17:26 UTC, sergeysergeevru commented on internal/app/service/auth/auth.go
> +	s.sessions[sessionID] = Session{
ты сессию хранишь в мапе, ок. Только в конкуретной записи можно получить панику https://go.dev/play/p/N6xNZGCGhAJ надо что-то потокобезопасное

2022-04-25 17:32 UTC, sergeysergeevru commented on internal/app/storage/transaction.go
> +		t.Login,
Лучше в базе хранить id пользователя.  В некоторых системах случается, что пользователю можно сменить логин в системе

2022-04-25 17:37 UTC, sergeysergeevru commented on internal/app/storage/transaction.go
> +	if *count > 0 {
если я правильно понял, то тебе запроса ниже должно быть достаточно

2022-04-25 17:42 UTC, sergeysergeevru commented on internal/app/storage/order.go
> +		"INSERT INTO orders (number, status, login, uploaded_at) VALUES ($1, $2, $3, NOW()) ON CONFLICT DO NOTHING RETURNING id",
аналогично, лучше хранить userId, а не логин

2022-04-25 17:44 UTC, sergeysergeevru commented on internal/app/storage/order.go
> +	}
хм, спорный такой вопрос. По природе не факт что здесь нужно ошибку возвращать... Но аргументов, что это плохо у меня нет, поэтому на твое усмотрение)

2022-04-25 17:46 UTC, sergeysergeevru commented on internal/app/model/transaction.go
> +	Login       string    `json:"-"`
как уже говорил ниже, правильнее будет userId

2022-04-25 17:46 UTC, sergeysergeevru commented on internal/app/model/order.go
> +	Login      string    `json:"-"`
тоже userId лучше здесь будет использовать

2022-04-25 17:49 UTC, sergeysergeevru commented on internal/app/gophermart/gophermart.go
> +    processed_at timestamptz NOT NULL);`
стоило бы подумать в сторону серьезных миграций. В настоящий момент я слабо представляю, как сервис будет деплоиться, когда нужно будет в схемы базы вносить изменения. Можешь глянуть goose библиотеку

2022-04-25 17:49 UTC, sergeysergeevru commented on internal/app/gophermart/gophermart.go
> +		log.Fatal("Failed to parse log level")
в таком случае уж лучше возвращать ошибку выше.

2022-04-25 17:51 UTC, sergeysergeevru commented on internal/app/gophermart/gophermart.go
> +	if err := db.Ping(); err != nil {
Если соединение удалось установить выше, то значит все норм должно быть.  Зачем пинговать сейчас?

2022-04-25 17:52 UTC, sergeysergeevru commented on internal/app/gophermart/gophermart.go
> +	}
как уже говорил, для миграций нужно что-то более совершенное. Чтобы сюда не лезть, если схема БД будет меняться

2022-04-25 17:56 UTC, sergeysergeevru commented on internal/app/controller/handlers_test.go
> +}
твоей сервер не должен знать о тестах, в таком случае получается ты тюнишь под тесты имплементацию

2022-04-25 17:58 UTC, sergeysergeevru commented on internal/app/controller/handlers.go
> +		err := c.UserRepository.RegisterUser(user)
если представить, что под getPasswordHash есть криптограция, то я бы унес это все в отдельный метод сервиса

2022-04-25 18:00 UTC, sergeysergeevru commented on internal/app/controller/handlers.go
> +		err := c.UserRepository.RegisterUser(user)
но это не страшно. А вот с хранением пароля стоит будет разобраться)

2022-04-25 18:09 UTC, sergeysergeevru commented on internal/app/controller/handlers.go
> +		user, err := c.UserAuthorizationStore.GetUser(r)
если я правильно понимаю, это твоя авторизация. Для начала ее бы лучше унести выше по коду хендлера, если клиент не авторизован, то делать нам нечего. Но вообще лучше бы вынести в middle ware а юзера можно передавать через контекст запрос. 
```

// допустим здесь выше у тебя передается var r *http.Request и ты определил что `user` это твой юзер. тогда можно сделать так
next.ServeHTTP(w, r.WithContext("user_key", user))
```

2022-04-25 18:15 UTC, sergeysergeevru commented on internal/app/controller/handlers.go
> +		defer resp.Body.Close()
этот код лучше обернуть в клиент для accrual

2022-04-25 18:15 UTC, sergeysergeevru commented on internal/app/controller/handlers.go
> +		defer resp.Body.Close()
по уровню что-то вроде репозитория должно получится, в общем твой дата провайдер)

2022-04-25 18:17 UTC, sergeysergeevru commented on internal/app/controller/handlers.go
> +func (c *Controller) UpdatePendingOrders(orders []string) error {
по природе это не является твоим контроллером. Я бы вынес это как сервис. Тут у тебя исключительно бизнес логика, если не говорить про запрос к accrual

2022-04-25 18:21 UTC, sergeysergeevru commented on internal/app/controller/handlers.go
> +			go c.UpdatePendingOrders(append(numbers, number))
на самом деле не вижу смысла запускать отдельно еще здесь горутину, если у тебя этот же ордер обработается UpdatePendingOrders. Либо тогда можно сделать воркер пул для обработки заказов. Вот как раз логику из c.UpdatePendingOrders можно запустить в виде воркера, чтобы он читал из канала. А здесь в хендлере ты можешь писать в канал. И в этот же канал писать из другой горутины, которая у тебя по расписанию выбирает из базы необработанные заказы.

2022-04-25 18:24 UTC, sergeysergeevru commented on internal/app/accrual/accrual.go
> +				err := controller.UpdatePendingOrders(orders)
как сказал ниже, логику из этого метода можно унести в воркер (и/или в добавок в слой app/service). Наверное самое большая проблема, что контроллер тут не сильно уместен. Контроллер (хендлер и т.п.) должны парсить входные данные и уже передавать слою бизнес логики.

2022-04-25 18:26 UTC, sergeysergeevru requested changes
В общем и целом, многое мне понравилось. Есть структура, в коде легко разбираться. Комменты оставил, из самых крупных проблем это конкурентный доступ к map и вопрос хранения пароля.

2022-04-27 11:32 UTC, vstebletsov89 commented on internal/app/controller/handlers.go
> +	PROCESSED  = "PROCESSED"
Исправил :)

2022-04-27 11:32 UTC, vstebletsov89 commented on internal/app/controller/handlers.go
> +func WriteJSON(w http.ResponseWriter, response interface{}, logger *logrus.Logger) {
Готово.

2022-04-27 11:35 UTC, vstebletsov89 commented on internal/app/controller/handlers.go
> +}
Согласен, исправил. Сделал криптографическое шифрование и дешифрование пароля через `crypto/aes`.

2022-04-27 11:37 UTC, vstebletsov89 commented on internal/app/controller/handlers.go
> +		}
Исправил здесь и в остальных похожих местах :)

2022-04-27 11:38 UTC, vstebletsov89 commented on internal/app/service/auth/auth.go
> +		b[i] = letterRunes[rand.Intn(len(letterRunes))]
Исправил, использовал UUID.

2022-04-27 11:39 UTC, vstebletsov89 commented on internal/app/service/auth/auth.go
> +		cookie, _ := r.Cookie(cookieName)
Исправил.

2022-04-27 11:40 UTC, vstebletsov89 commented on internal/app/service/auth/auth.go
> +var _ secure.UserAuthorization = (*UserAuthorizationStore)(nil)
Спасибо)

2022-04-27 11:42 UTC, vstebletsov89 commented on internal/app/service/auth/auth.go
> +	s.sessions[sessionID] = Session{
Исправил используя sync.RWMutex во время записи в мапу. Надеюсь сейчас ок.

2022-04-27 11:44 UTC, vstebletsov89 commented on internal/app/storage/transaction.go
> +		t.Login,
Исправил, теперь храню userID вместо логина во всех таблицах в БД. Логин теперь хранится только в таблице users.

2022-04-27 11:45 UTC, vstebletsov89 commented on internal/app/storage/transaction.go
> +	if *count > 0 {
Исправил.

2022-04-27 11:45 UTC, vstebletsov89 commented on internal/app/storage/order.go
> +		"INSERT INTO orders (number, status, login, uploaded_at) VALUES ($1, $2, $3, NOW()) ON CONFLICT DO NOTHING RETURNING id",
Исправил.

2022-04-27 11:49 UTC, vstebletsov89 commented on internal/app/storage/order.go
> +	}
Оставил как есть, т.к. при этой ошибке возвращаecя определенный статус код ответа (StatusNoContent).

2022-04-27 11:50 UTC, vstebletsov89 commented on internal/app/model/transaction.go
> +	Login       string    `json:"-"`
Исправил.

2022-04-27 11:50 UTC, vstebletsov89 commented on internal/app/model/order.go
> +	Login      string    `json:"-"`
Исправил.

2022-04-27 11:51 UTC, vstebletsov89 commented on internal/app/gophermart/gophermart.go
> +    processed_at timestamptz NOT NULL);`
Спасибо за подсказку! Переделал миграции с использованием goose библиотеки.

2022-04-27 11:52 UTC, vstebletsov89 commented on internal/app/gophermart/gophermart.go
> +		log.Fatal("Failed to parse log level")
Исправил.

2022-04-27 11:52 UTC, vstebletsov89 commented on internal/app/gophermart/gophermart.go
> +	if err := db.Ping(); err != nil {
Согласен, удалил.

2022-04-27 11:52 UTC, vstebletsov89 commented on internal/app/gophermart/gophermart.go
> +	}
Исправил на goose миграции.

2022-04-27 11:55 UTC, vstebletsov89 commented on internal/app/controller/handlers.go
> +		err := c.UserRepository.RegisterUser(user)
Переделал, надеюсь сейчас выглядит ок :)

2022-04-27 11:57 UTC, vstebletsov89 commented on internal/app/controller/handlers.go
> +		user, err := c.UserAuthorizationStore.GetUser(r)
Хорошая идея, исправил. Теперь авторизация делается только один раз в middleware и передаю через контекст userID дальше.

2022-04-27 11:58 UTC, vstebletsov89 commented on internal/app/controller/handlers.go
> +		defer resp.Body.Close()
Сделал клиент для accrual)

2022-04-27 11:59 UTC, vstebletsov89 commented on internal/app/controller/handlers.go
> +func (c *Controller) UpdatePendingOrders(orders []string) error {
Сделал это методом клиента accrual.

2022-04-27 12:01 UTC, vstebletsov89 commented on internal/app/controller/handlers.go
> +			go c.UpdatePendingOrders(append(numbers, number))
Убрал запуск горутины отсюда.

2022-04-27 12:01 UTC, vstebletsov89 commented on internal/app/accrual/accrual.go
> +				err := controller.UpdatePendingOrders(orders)
Убрал в accrual клиент.

2022-04-27 12:07 UTC, vstebletsov89 commented on internal/app/controller/handlers.go
> +		if err := json.NewDecoder(r.Body).Decode(&user); err != nil {
Попробовал убрать '&', но тогда начинают падать юнит тесты:
```
FAIL: TestRegisterHandler/RegisterHandler_(empty_login) (0.00s)
        handlers_test.go:397:
                Error Trace:    handlers_test.go:397
                Error:          Not equal:
                                expected: ""
                                actual  : "json: Unmarshal(nil *model.User)"
```

2022-04-28 17:18 UTC, sergeysergeevru commented on internal/app/gophermart/migrations/00001_users_table.sql
> +CREATE TABLE IF NOT EXISTS "users" (
по факту, все 3 миграции можно объединить в одну :) Суть миграций сделать возможным преобразование схем БД во время имплементаций новых фич, а если на начальном этапе мы знаем про все 3 таблицы, то можно одной миграцией их и создавать. С другой стороны можем предположить, что мы итерационно имплементировали  сначала юзеров, а потом фичи про ордера и транзакции подъехали. Сейчас вполне норм)

2022-04-28 17:25 UTC, sergeysergeevru commented on internal/app/controller/handlers.go
> +		if err := json.NewDecoder(r.Body).Decode(&user); err != nil {
Ах да, де факто на строчке `var user *model.User`. user пуст и представляет себя nil. И ты со сути берешь адрес от пустоты.

2022-04-28 17:32 UTC, sergeysergeevru commented on internal/app/service/auth/cipher.go
> +	"math/rand"
math/rand для генерации ключей лучше не использовать. Он не является безопасным, для генерации различных ключей

2022-04-28 17:36 UTC, sergeysergeevru commented on internal/app/service/auth/cipher.go
> +}
тут ты инициализируешь новый ключ на каждый новый запуск приложения. Есть большой минус: как только мы выходим в прод, то если у нас один истанс, то любое падение приложения или новый деплой сделает невалидными пароли пользователей которые зарегистрировались ранее.

2022-04-28 17:41 UTC, sergeysergeevru commented on internal/app/service/auth/cipher.go
> +}
Вообще не думаю что шифрование пароля достаточно безопасный метод: в контексте аутентификации. Если уплывет база пользователей и ключ шифрования, то это очень серьезная репутационная проблема. Лучше применять что-то одностороннее: хэширование или специальные функции хранения ключей, например bcrypt, scrypt и т.п. Симметричную криптографию для подобных целей не стоит использовать.

2022-04-28 17:46 UTC, sergeysergeevru commented on internal/app/service/auth/auth.go
> +	s.sessions[sessionID] = Session{
Нуу почти) ReadLock стоит еще поставить ниже, когда обращаешься к мапе

2022-04-28 18:28 UTC, sergeysergeevru commented on internal/app/accrual/client.go
> +}
Это у тебя уже не клиент, а сервис получился)

2022-04-28 18:32 UTC, sergeysergeevru commented on internal/app/accrual/client.go
> +		defer resp.Body.Close()
клиентом по сути должен стать этот кусок, чтобы его можно было бы заменить на
```suggestion
		order, err := c.accuralProvider.GetOrder(o)
```

2022-04-28 18:34 UTC, sergeysergeevru commented on internal/app/accrual/client.go
> +}
Задача клиентов (дата провайдеров и тому подобных) делать запросы/извлекать данные откуда бы ни было. тут у тебя уже бизнес пошел.

2022-04-28 18:35 UTC, sergeysergeevru commented on internal/app/accrual/client.go
> +		defer resp.Body.Close()
Бенефит от клиента в том, что если однажды внутри системы будет запущен accural 2.0 имеющий (допустим) другой протокол взаимодействия, то тебе будет достаточно написано новый клиент и подменить в бизнес логике.

2022-04-28 18:41 UTC, sergeysergeevru commented on internal/app/accrual/client.go
> +package accrual
оставлю здесь коммент, но он касается директорий: вероятно можно app убрать:
`internal/app/accrual/client.go` -> `internal/accrual/client.go` это касается всех файлов ниже. Понятно, под app обычно понимают (во всяком случае я) слой бизнес логики, а у тебя там закинуты стораджы, модели, хендлеры и тому подобное.

2022-04-28 18:47 UTC, sergeysergeevru approved these changes
Смотрится достойно. Оставил некоторые рекомендации по улучшению и указал на некоторые проблемы. Думаю я дал достаточно прямолинейные советы, будем считать дополнительное ревью будет излишнем. Работу принимаю. Если будут какие-то вопросы по доработке, то всегда велком в чат :)

2022-06-02 08:18 UTC, merged